@extends('general.index', $setup)
@section('cardbody')
<form action="{{ $setup['action'] }}" method="POST" enctype="multipart/form-data" id="categoryForm">
    @csrf
    @isset($setup['isupdate'])
        @method('PUT')
    @endisset

    <div class="row">
        <!-- Main Content Column -->
        <div class="col-md-8">
            <div class="card mb-4">
                <div class="card-body">
                    <!-- Basic Information -->
                    @foreach($fields as $field)
                        @if(in_array($field['id'], ['name', 'slug', 'description', 'icon']))
                            @include('partials.fields', ['fields' => [$field]])
                        @endif
                    @endforeach
                </div>
            </div>
        </div>

        <!-- Sidebar Settings -->
        <div class="col-md-4">
            <!-- Settings Panel -->
            <div class="card mb-4">
                <div class="card-header">
                    <h4 class="card-title mb-0">Settings</h4>
                </div>
                <div class="card-body">
                    @foreach($fields as $field)
                        @if(in_array($field['id'], ['sort_order', 'is_active']))
                            @include('partials.fields', ['fields' => [$field]])
                        @endif
                    @endforeach
                    
                    <div class="text-end mt-3">
                        @if (isset($setup['isupdate']))
                            <button type="submit" class="btn btn-primary">{{ __('Update Category')}}</button>  
                        @else
                            <button type="submit" class="btn btn-primary">{{ __('Create Category')}}</button>  
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<style>
.card {
    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    margin-bottom: 1rem;
}
.card-header {
    background-color: #f8f9fa;
    border-bottom: 1px solid rgba(0,0,0,.125);
}
.card-title {
    font-size: 1.1rem;
    font-weight: 500;
}
.card-body .form-control,
.card-body .form-select {
    width: 100%;
    margin-bottom: 1rem;
}
.card-body .form-check {
    padding: 1rem 0;
}
.card-body label {
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 500;
    color: #495057;
}
</style>

@section('head')
    <!-- Font Awesome for Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <script>
        // Enhanced slug generation function
        function generateSlug(text) {
            return text
                .toLowerCase()
                .replace(/[áàãâä]/g, 'a')
                .replace(/[éèêë]/g, 'e')
                .replace(/[íìîï]/g, 'i')
                .replace(/[óòõôö]/g, 'o')
                .replace(/[úùûü]/g, 'u')
                .replace(/[ýÿ]/g, 'y')
                .replace(/[ñ]/g, 'n')
                .replace(/[ç]/g, 'c')
                .replace(/&/g, 'and')
                .replace(/\+/g, 'plus')
                .replace(/\$/g, 'dollar')
                .replace(/€/g, 'euro')
                .replace(/£/g, 'pound')
                .replace(/[^a-z0-9\s-]/g, ' ')
                .replace(/\s+/g, ' ')
                .trim()
                .replace(/\s/g, '-')
                .replace(/-+/g, '-')
                .substring(0, 60)
                .replace(/-$/, '');
        }

        document.addEventListener('DOMContentLoaded', function() {
            const nameInput = document.querySelector('input[name="name"]');
            const slugInput = document.querySelector('input[name="slug"]');
            const isEditMode = {{ isset($setup['isupdate']) ? 'true' : 'false' }};
            
            // Initialize slug generation
            if (nameInput && slugInput && !isEditMode) {
                nameInput.addEventListener('input', function() {
                    if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
                        const slugValue = generateSlug(this.value);
                        slugInput.value = slugValue;
                        slugInput.dataset.autoGenerated = 'true';
                    }
                });

                slugInput.addEventListener('input', function() {
                    this.dataset.autoGenerated = 'false';
                });
            }
        });
    </script>
@endsection
@endsection
